version: "3"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ehrbase
      POSTGRES_USER: ehrbase
      POSTGRES_PASSWORD: ehrbase
    volumes:
      - db-data:/var/lib/postgresql/data

  ehrbase:
    image: ehrbase/ehrbase:next
    environment:
      SPRING_DATASOURCE_URL : "jdbc:postgresql://db:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME : ehrbase
      SPRING_DATASOURCE_PASSWORD : ehrbase
      SERVER_AQLCONFIG_USEJSQUERY : "false"
    depends_on:
      - db
    ports:
      - "8080:8080"

  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8888:8080"
    depends_on:
      - db

  # hapi-fhir-postgres:
  #   image: postgres:13-alpine
  #   container_name: hapi-fhir-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: "ehrbase"
  #     POSTGRES_USER: "ehrbase"
  #     POSTGRES_PASSWORD: "ehrbase"
  #   volumes:
  #     - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  db-data:
